Feature/admin product
teamdev-ecommerce-202409/E-Commerce-Webapp-with-Stripe-Sync_Front pull request #10
Opened 2024-10-17 17:07 UTC by haru864

管理者ダッシュボードの製品一覧・詳細画面を実装
一覧：バックエンドからProduct一覧を取得して表示、フィルタリング機能付き
詳細：登録データを初期値として表示、更新ボタン押下でデータ登録

2024-10-18 13:38 UTC, Karukan0814 approved these changes
いちおう、コメントしておきました。cssはあんまり気にしなくてよいと思います

2024-10-18 13:38 UTC, Karukan0814 commented on src/lib/database/Product.ts
> +export async function updateProductDetail(
削除機能を物理削除ではなく論理削除で実装する場合、isDeletedを任意引数として追加することでメソッドの流用が可能

2024-10-18 13:38 UTC, Karukan0814 commented on src/pages/AdminProductDetailPage.tsx
> +  const updateProduct = async () => {
入力チェックがあんまり入っていないけど、今後余裕あったら

2024-10-19 19:03 UTC, haru864 commented on src/pages/AdminProductDetailPage.tsx
> +  const updateProduct = async () => {
入力チェックを追加しました。

2024-10-19 19:05 UTC, haru864 commented
@Karukan0814 @yadon
レビュー指摘を取り込んだ後、新規作成と削除の実装もこのブランチでやります。
終わったら連絡するので、マージは待ってほしいです。

2024-10-23 15:54 UTC, haru864 commented
@Karukan0814 @sunny-side-app 
製品追加・削除機能を実装したので、レビューお願いします！

2024-10-26 00:24 UTC, Karukan0814 requested changes
レビュー追加しました。変更要望

2024-10-26 00:24 UTC, Karukan0814 commented on src/lib/database/Product.ts
> +function checkProductUpdateParam(params: { [key: string]: unknown }) {
入力チェックのかけ方として、論理上は間違ってはいません。ただ、Reactの設計上は、入力チェックは画面コンポーネントの仕事として位置づけられ、LoginForm.tsxのように画面コンポーネントもしくはそれの子コンポーネント内で行われることが多いです。また、文字数制限くらいの入力チェックはreact-hook-form等に任せるか、muiのTextFieldを使用するのであればinputPropsを設定して制限をかけてしまいます。
もちろん、データの更新時の入力チェックを全て各画面コンポーネントに任せるのは不安、ということは十分考えられるので今回のようにDB接続時にも入力チェックをかけるのはありです。ただ、それはまず画面コンポーネントで入力チェックかけてから、が一般的です。こちらの方がパフォーマンスがいいのでUIとして◎。ですので、文字数制限は画面側でもかけてください。
https://zenn.dev/enish/articles/5cc332d3eeb1a7
ただ、実現したい結果は出ているので、今回のレビューとしてはOKなので、余裕あれば手をつけてください。

2024-10-26 00:24 UTC, Karukan0814 commented on src/pages/AdminProductDetailPage.tsx
> +  const productId = Number(location.state);
productIdをlocation.stateで受け取ると、detailPageにリスト画面から遷移しないとたどり着けなくなる。例えば、urlで直接、"/admin/detail?productId=1"みたいなのを打って、直接その詳細画面にとべなくなる。ので、useParamsでクエリパラムを受け取ったほうがよい

2024-10-26 00:24 UTC, Karukan0814 commented on src/pages/AdminProductDetailPage.tsx
> +    updateProduct();
await　かけないとupdateProductの処理が終わる前にnavigate(`/admin/product`);がはしることになる

2024-10-26 00:24 UTC, Karukan0814 commented on src/pages/AdminProductDetailPage.tsx
> +    deleteProduct();
await　かけないと deleteProductの処理が終わる前にnavigate(/admin/product);がはしることになる

2024-10-26 00:24 UTC, Karukan0814 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
> +      for (const product of productList) {
const productInfo = productList.find((product) => product.id === productId);で簡潔になる

2024-10-26 00:24 UTC, Karukan0814 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
>          updateProductDetail(
awaitをかけていないし、かけたとしても×になっちゃいます。。逐一await呼ぶはユーザーエクスペリエンス悪くなる。
こういった処理の場合、for文の中でバックエンドAPIを連続して呼ぶのはパフォーマンスが遅くなるので、NG判定がでます。通常は削除したいIDのリストをバックエンドに配列で渡す。バックエンドは指定されたIDを一気に削除します。roduct.objects.filter(id__in=product_ids).update(is_deleted=False)　
このまま、for文の中でidごとに逐一APIを呼ぶ方式をとる場合、最低限、Promise.allで並列処理かけるのがよろし。でも、私としては前者の配列渡しを推したい・・・！

2024-10-26 00:24 UTC, Karukan0814 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
> +    alert(`${deletedProductCount}件削除しました。`);
現状だと、削除し終わったときに削除したproductが画面から消えていないのではないかな、と思います。これは修正しないといけない。
reactで配列操作する場合は、setProductListに新たな配列を入れることになります。このコンポーネントにproductListを渡してきている親コンポーネントにsetProductListも渡してもらって、削除後の配列をセットして表示したらどうでしょう。
もしくは、親コンポ―ネントの useEffect(() => {
    fetchFilteredProducts();
  }, [page]);を子コンポーネントから起動させる方法を考えるか。
ちょっとここら辺はreactのややこしいところなので、これで激詰まりしたらかるかんを呼んでください。

2024-10-26 16:37 UTC, haru864 commented on src/lib/database/Product.ts
> +function checkProductUpdateParam(params: { [key: string]: unknown }) {
入力チェックを追加しました。
3e01db4e00368de219e994e4487837c21df48b50

2024-10-26 17:24 UTC, haru864 commented on src/pages/AdminProductDetailPage.tsx
> +  const productId = Number(location.state);
useParams()でURLからIDを取得するようにしました。
ac7709f0482109acab5e1f59f021968d47e679e8

2024-10-27 08:49 UTC, haru864 commented on src/pages/AdminProductDetailPage.tsx
> +    updateProduct();
await追加しました。
5f0a9cadd0fe6f970d6836a76342b413285de2f1

2024-10-27 08:49 UTC, haru864 commented on src/pages/AdminProductDetailPage.tsx
> +    deleteProduct();
await追加しました。
5f0a9cadd0fe6f970d6836a76342b413285de2f1

2024-10-27 08:58 UTC, haru864 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
> +      for (const product of productList) {
修正しました。
e603f9d4961e8e99345f0377864b6c172a2d4eb5

2024-10-27 13:36 UTC, haru864 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
>          updateProductDetail(
配列渡しで論理削除できるようにしました。
979f1fef2c51ef8c7b18122c76418c12a026cafc

2024-10-27 14:14 UTC, haru864 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
> +    alert(`${deletedProductCount}件削除しました。`);
画面が更新されるようにしました。
9a904ffcb7adac952c2f55734a5c2c9adb4ab896

2024-10-27 14:15 UTC, haru864 commented
@Karukan0814 
ご指摘あったところを修正しました。
確認お願いします。

2024-11-01 13:31 UTC, Karukan0814 requested changes

2024-11-01 13:31 UTC, Karukan0814 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
> +      deleteProducts(checkedProductIds);
awaitかけてくださいませ。
追加指摘はこれだけです。

2024-11-02 14:12 UTC, haru864 commented on src/component/featured/AdminHomePage/AdminProductList.tsx
> +      deleteProducts(checkedProductIds);
@Karukan0814 
直しました。
2d5f2daf387204e4cc9ef2aeb38aceec963b924d

2024-11-03 09:10 UTC, merged