Feature/mypage order history
teamdev-ecommerce-202409/E-Commerce-Webapp-with-Stripe-Sync_Front pull request #13
Opened 2024-10-27 07:47 UTC by sunny-side-app

マイページへの画面遷移と注文履歴一覧表示のレビューをお願いします。
マイページ画面における下記機能は別途改修予定です。

- プロフィールと注文履歴の切り替え表示
- 認証機能の組み込み

2024-10-27 14:52 UTC, haru864 requested changes

2024-10-27 14:52 UTC, haru864 commented on src/lib/jotai/atoms/user.ts
> +    user_name: "doinkya",
nameは空文字にすべきだと思います。

2024-10-27 14:52 UTC, haru864 commented on src/lib/jotai/atoms/user.ts
> +  authtoken: "sample-token", // グローバルなauthtoken
コメント削除して、global_auth_tokenにすべきでは。

2024-10-27 14:52 UTC, haru864 commented on src/lib/database/Order.ts
コメント全部削除して、行間詰めてほしいです。

2024-10-28 10:18 UTC, sunny-side-app commented
下記指摘対応させていただきました。authtokenはUserInfoType.tsでも利用されているためコメント削除のみ対応しました。

> nameは空文字にすべきだと思います。
> コメント削除して、global_auth_tokenにすべきでは。
> コメント全部削除して、行間詰めてほしいです。

2024-10-28 10:44 UTC, haru864 requested changes

2024-10-28 10:44 UTC, haru864 commented on src/lib/database/Order.ts
>  // UserIDからorder historyを取得する
これも消してほしいです

2024-10-28 10:54 UTC, sunny-side-app commented
消し漏れ失礼しました。修正しました。

2024-10-28 10:54 UTC, sunny-side-app commented on src/lib/database/Order.ts
>  // UserIDからorder historyを取得する
消し漏れ失礼しました。修正しました。

2024-10-28 11:59 UTC, merged