Feature/get product data from backend
teamdev-ecommerce-202409/E-Commerce-Webapp-with-Stripe-Sync_Front pull request #6
Opened 2024-10-08 15:11 UTC by Karukan0814

2024-10-08 15:41 UTC, Karukan0814 commented
Home画面のフィルタリング機能とバックエンド側のAPIを紐づけました。＋Detail画面のバックエンドからの商品情報取得

2024-10-10 11:34 UTC, haru864 requested changes

2024-10-10 11:34 UTC, haru864 commented on src/lib/database/Product.ts
> +      params.userId = productId;
userIdじゃなくてproductIdではないでしょうか

2024-10-10 11:34 UTC, haru864 commented on src/pages/DetailPage.tsx
> +// import { testItems } from "../lib/testData/testData";
使わないのであれば削除したいです

2024-10-10 11:34 UTC, haru864 commented on src/pages/DetailPage.tsx
>  // import CategorySelectBox from "../component/featured/DetailPage/CategorySelectBox";
これも削除

2024-10-10 11:34 UTC, haru864 commented on src/pages/DetailPage.tsx
> +      // }
コメントアウトは削除

2024-10-10 11:34 UTC, haru864 commented on src/style/ProductList.css
> +  /* grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); */
コメントアウトは削除

2024-10-10 13:42 UTC, merged